# Generated by Django 3.1.7 on 2021-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210318_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='msgId',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
