# Generated by Django 3.1.7 on 2021-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210314_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
