# Generated by Django 3.1.7 on 2021-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210318_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msgId',
            new_name='msg_Id',
        ),
    ]
